# Generated by Django 5.0.2 on 2024-02-21 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.catergory'),
        ),
    ]
