# Generated by Django 5.0.2 on 2024-02-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.catergory'),
        ),
    ]
