# Generated by Django 5.0.2 on 2024-02-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_catergory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catergory',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
