# Generated by Django 5.0.2 on 2024-02-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_catergory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
