# Generated by Django 5.0.2 on 2024-02-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
